FROM wordpress:6.0.1-php8.1-apache
ADD --chmod=0755 https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/
# Make this crash :_)
# RUN install-php-extensions uopz
# RUN install-php-extensions xdebug-^3@stable